// TODO: transfter googleApiKey to .env
export const googleApiKey = 'AIzaSyA8vejxIx686PpYxiXBqGpovVCZRurJBLQ';

export const continents = [
  { code: 'AD', name: 'Europe' },
  { code: 'AE', name: 'Asia' },
  { code: 'AF', name: 'Asia' },
  { code: 'AG', name: 'North America' },
  { code: 'AI', name: 'North America' },
  { code: 'AL', name: 'Europe' },
  { code: 'AM', name: 'Asia' },
  { code: 'AN', name: 'North America' },
  { code: 'AO', name: 'Africa' },
  { code: 'AQ', name: 'Antarctica' },
  { code: 'AR', name: 'South America' },
  { code: 'AS', name: 'Australia' },
  { code: 'AT', name: 'Europe' },
  { code: 'AU', name: 'Australia' },
  { code: 'AW', name: 'North America' },
  { code: 'AZ', name: 'Asia' },
  { code: 'BA', name: 'Europe' },
  { code: 'BB', name: 'North America' },
  { code: 'BD', name: 'Asia' },
  { code: 'BE', name: 'Europe' },
  { code: 'BF', name: 'Africa' },
  { code: 'BG', name: 'Europe' },
  { code: 'BH', name: 'Asia' },
  { code: 'BI', name: 'Africa' },
  { code: 'BJ', name: 'Africa' },
  { code: 'BM', name: 'North America' },
  { code: 'BN', name: 'Asia' },
  { code: 'BO', name: 'South America' },
  { code: 'BR', name: 'South America' },
  { code: 'BS', name: 'North America' },
  { code: 'BT', name: 'Asia' },
  { code: 'BW', name: 'Africa' },
  { code: 'BY', name: 'Europe' },
  { code: 'BZ', name: 'North America' },
  { code: 'CA', name: 'North America' },
  { code: 'CC', name: 'Asia' },
  { code: 'CD', name: 'Africa' },
  { code: 'CF', name: 'Africa' },
  { code: 'CG', name: 'Africa' },
  { code: 'CH', name: 'Europe' },
  { code: 'CI', name: 'Africa' },
  { code: 'CK', name: 'Australia' },
  { code: 'CL', name: 'South America' },
  { code: 'CM', name: 'Africa' },
  { code: 'CN', name: 'Asia' },
  { code: 'CO', name: 'South America' },
  { code: 'CR', name: 'North America' },
  { code: 'CU', name: 'North America' },
  { code: 'CV', name: 'Africa' },
  { code: 'CX', name: 'Asia' },
  { code: 'CY', name: 'Asia' },
  { code: 'CZ', name: 'Europe' },
  { code: 'DE', name: 'Europe' },
  { code: 'DJ', name: 'Africa' },
  { code: 'DK', name: 'Europe' },
  { code: 'DM', name: 'North America' },
  { code: 'DO', name: 'North America' },
  { code: 'DZ', name: 'Africa' },
  { code: 'EC', name: 'South America' },
  { code: 'EE', name: 'Europe' },
  { code: 'EG', name: 'Africa' },
  { code: 'EH', name: 'Africa' },
  { code: 'ER', name: 'Africa' },
  { code: 'ES', name: 'Europe' },
  { code: 'ET', name: 'Africa' },
  { code: 'FI', name: 'Europe' },
  { code: 'FJ', name: 'Australia' },
  { code: 'FK', name: 'South America' },
  { code: 'FM', name: 'Australia' },
  { code: 'FO', name: 'Europe' },
  { code: 'FR', name: 'Europe' },
  { code: 'GA', name: 'Africa' },
  { code: 'GB', name: 'Europe' },
  { code: 'GD', name: 'North America' },
  { code: 'GE', name: 'Asia' },
  { code: 'GF', name: 'South America' },
  { code: 'GG', name: 'Europe' },
  { code: 'GH', name: 'Africa' },
  { code: 'GI', name: 'Europe' },
  { code: 'GL', name: 'North America' },
  { code: 'GM', name: 'Africa' },
  { code: 'GN', name: 'Africa' },
  { code: 'GP', name: 'North America' },
  { code: 'GQ', name: 'Africa' },
  { code: 'GR', name: 'Europe' },
  { code: 'GS', name: 'Antarctica' },
  { code: 'GT', name: 'North America' },
  { code: 'GU', name: 'Australia' },
  { code: 'GW', name: 'Africa' },
  { code: 'GY', name: 'South America' },
  { code: 'HK', name: 'Asia' },
  { code: 'HN', name: 'North America' },
  { code: 'HR', name: 'Europe' },
  { code: 'HT', name: 'North America' },
  { code: 'HU', name: 'Europe' },
  { code: 'ID', name: 'Asia' },
  { code: 'IE', name: 'Europe' },
  { code: 'IL', name: 'Asia' },
  { code: 'IM', name: 'Europe' },
  { code: 'IN', name: 'Asia' },
  { code: 'IO', name: 'Asia' },
  { code: 'IQ', name: 'Asia' },
  { code: 'IR', name: 'Asia' },
  { code: 'IS', name: 'Europe' },
  { code: 'IT', name: 'Europe' },
  { code: 'JE', name: 'Europe' },
  { code: 'JM', name: 'North America' },
  { code: 'JO', name: 'Asia' },
  { code: 'JP', name: 'Asia' },
  { code: 'KE', name: 'Africa' },
  { code: 'KG', name: 'Asia' },
  { code: 'KH', name: 'Asia' },
  { code: 'KI', name: 'Australia' },
  { code: 'KM', name: 'Africa' },
  { code: 'KN', name: 'North America' },
  { code: 'KP', name: 'Asia' },
  { code: 'KR', name: 'Asia' },
  { code: 'KW', name: 'Asia' },
  { code: 'KY', name: 'North America' },
  { code: 'KZ', name: 'Asia' },
  { code: 'LA', name: 'Asia' },
  { code: 'LB', name: 'Asia' },
  { code: 'LC', name: 'North America' },
  { code: 'LI', name: 'Europe' },
  { code: 'LK', name: 'Asia' },
  { code: 'LR', name: 'Africa' },
  { code: 'LS', name: 'Africa' },
  { code: 'LT', name: 'Europe' },
  { code: 'LU', name: 'Europe' },
  { code: 'LV', name: 'Europe' },
  { code: 'LY', name: 'Africa' },
  { code: 'MA', name: 'Africa' },
  { code: 'MC', name: 'Europe' },
  { code: 'MD', name: 'Europe' },
  { code: 'ME', name: 'Europe' },
  { code: 'MG', name: 'Africa' },
  { code: 'MH', name: 'Australia' },
  { code: 'MK', name: 'Europe' },
  { code: 'ML', name: 'Africa' },
  { code: 'MM', name: 'Asia' },
  { code: 'MN', name: 'Asia' },
  { code: 'MO', name: 'Asia' },
  { code: 'MP', name: 'Australia' },
  { code: 'MQ', name: 'North America' },
  { code: 'MR', name: 'Africa' },
  { code: 'MS', name: 'North America' },
  { code: 'MT', name: 'Europe' },
  { code: 'MU', name: 'Africa' },
  { code: 'MV', name: 'Asia' },
  { code: 'MW', name: 'Africa' },
  { code: 'MX', name: 'North America' },
  { code: 'MY', name: 'Asia' },
  { code: 'MZ', name: 'Africa' },
  { code: 'NA', name: 'Africa' },
  { code: 'NC', name: 'Australia' },
  { code: 'NE', name: 'Africa' },
  { code: 'NF', name: 'Australia' },
  { code: 'NG', name: 'Africa' },
  { code: 'NI', name: 'North America' },
  { code: 'NL', name: 'Europe' },
  { code: 'NO', name: 'Europe' },
  { code: 'NP', name: 'Asia' },
  { code: 'NR', name: 'Australia' },
  { code: 'NU', name: 'Australia' },
  { code: 'NZ', name: 'Australia' },
  { code: 'OM', name: 'Asia' },
  { code: 'PA', name: 'North America' },
  { code: 'PE', name: 'South America' },
  { code: 'PF', name: 'Australia' },
  { code: 'PG', name: 'Australia' },
  { code: 'PH', name: 'Asia' },
  { code: 'PK', name: 'Asia' },
  { code: 'PL', name: 'Europe' },
  { code: 'PM', name: 'North America' },
  { code: 'PN', name: 'Australia' },
  { code: 'PR', name: 'North America' },
  { code: 'PS', name: 'Asia' },
  { code: 'PT', name: 'Europe' },
  { code: 'PW', name: 'Australia' },
  { code: 'PY', name: 'South America' },
  { code: 'QA', name: 'Asia' },
  { code: 'RE', name: 'Africa' },
  { code: 'RO', name: 'Europe' },
  { code: 'RS', name: 'Europe' },
  { code: 'RU', name: 'Europe' },
  { code: 'RW', name: 'Africa' },
  { code: 'SA', name: 'Asia' },
  { code: 'SB', name: 'Australia' },
  { code: 'SC', name: 'Africa' },
  { code: 'SD', name: 'Africa' },
  { code: 'SE', name: 'Europe' },
  { code: 'SG', name: 'Asia' },
  { code: 'SH', name: 'Africa' },
  { code: 'SI', name: 'Europe' },
  { code: 'SJ', name: 'Europe' },
  { code: 'SK', name: 'Europe' },
  { code: 'SL', name: 'Africa' },
  { code: 'SM', name: 'Europe' },
  { code: 'SN', name: 'Africa' },
  { code: 'SO', name: 'Africa' },
  { code: 'SR', name: 'South America' },
  { code: 'ST', name: 'Africa' },
  { code: 'SV', name: 'North America' },
  { code: 'SY', name: 'Asia' },
  { code: 'SZ', name: 'Africa' },
  { code: 'TC', name: 'North America' },
  { code: 'TD', name: 'Africa' },
  { code: 'TF', name: 'Antarctica' },
  { code: 'TG', name: 'Africa' },
  { code: 'TH', name: 'Asia' },
  { code: 'TJ', name: 'Asia' },
  { code: 'TK', name: 'Australia' },
  { code: 'TM', name: 'Asia' },
  { code: 'TN', name: 'Africa' },
  { code: 'TO', name: 'Australia' },
  { code: 'TR', name: 'Asia' },
  { code: 'TT', name: 'North America' },
  { code: 'TV', name: 'Australia' },
  { code: 'TW', name: 'Asia' },
  { code: 'TZ', name: 'Africa' },
  { code: 'UA', name: 'Europe' },
  { code: 'UG', name: 'Africa' },
  { code: 'US', name: 'North America' },
  { code: 'UY', name: 'South America' },
  { code: 'UZ', name: 'Asia' },
  { code: 'VC', name: 'North America' },
  { code: 'VE', name: 'South America' },
  { code: 'VG', name: 'North America' },
  { code: 'VI', name: 'North America' },
  { code: 'VN', name: 'Asia' },
  { code: 'VU', name: 'Australia' },
  { code: 'WF', name: 'Australia' },
  { code: 'WS', name: 'Australia' },
  { code: 'YE', name: 'Asia' },
  { code: 'YT', name: 'Africa' },
  { code: 'ZA', name: 'Africa' },
  { code: 'ZM', name: 'Africa' },
  { code: 'ZW', name: 'Africa' },
];
